//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.23 at 10:52:42 AM EEST 
//


package com.example.catalogue.backend.api.webservice.autogen;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.catalogue.api.webservice.autogen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.catalogue.api.webservice.autogen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllCoursesRequest }
     * 
     */
    public GetAllCoursesRequest createGetAllCoursesRequest() {
        return new GetAllCoursesRequest();
    }

    /**
     * Create an instance of {@link GetAllCoursesResponse }
     * 
     */
    public GetAllCoursesResponse createGetAllCoursesResponse() {
        return new GetAllCoursesResponse();
    }

    /**
     * Create an instance of {@link CourseXml }
     * 
     */
    public CourseXml createCourseXml() {
        return new CourseXml();
    }

    /**
     * Create an instance of {@link GetCourseByIdRequest }
     * 
     */
    public GetCourseByIdRequest createGetCourseByIdRequest() {
        return new GetCourseByIdRequest();
    }

    /**
     * Create an instance of {@link GetCourseByIdResponse }
     * 
     */
    public GetCourseByIdResponse createGetCourseByIdResponse() {
        return new GetCourseByIdResponse();
    }

    /**
     * Create an instance of {@link CreateCourseRequest }
     * 
     */
    public CreateCourseRequest createCreateCourseRequest() {
        return new CreateCourseRequest();
    }

    /**
     * Create an instance of {@link CreateCourseResponse }
     * 
     */
    public CreateCourseResponse createCreateCourseResponse() {
        return new CreateCourseResponse();
    }

}
