apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: course-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: course-catalogue-backend:0.1
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              value: prod
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -w 1 mysql 3306; do sleep 1; done;' ]


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: course-catalogue
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
