apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: course-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: course-catalogue-frontend:0.1
          ports:
            - containerPort: 9090
          env:
            - name: spring.profiles.active
              value: prod
            - name: backend_address
              value: http://backend:8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: course-catalogue
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
